# Generated by Django 2.1.4 on 2018-12-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0003_auto_20181209_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='begin_time',
            field=models.DateField(),
        ),
    ]
