# Generated by Django 2.1.4 on 2018-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0005_auto_20181211_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='url',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
