# Generated by Django 2.1.4 on 2018-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0006_auto_20181211_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
