# Generated by Django 2.1.4 on 2018-12-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0008_auto_20181212_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
