# Generated by Django 2.1.4 on 2018-12-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0013_auto_20181212_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_time',
            field=models.CharField(default='2018-12-12', max_length=30),
        ),
    ]
