# Generated by Django 2.1.4 on 2018-12-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0014_auto_20181213_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_time',
            field=models.CharField(default='2018-12-12', max_length=20),
        ),
    ]
