# Generated by Django 2.1.4 on 2018-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0017_auto_20181214_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_price1',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
