# Generated by Django 2.1.4 on 2018-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0018_goods_goods_price1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bool_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
