# Generated by Django 2.1.4 on 2018-12-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0019_auto_20181214_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.TextField(),
        ),
    ]
