# Generated by Django 2.1.4 on 2018-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0020_auto_20181215_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheet',
            name='final_price',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='ordersheet',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ordersheet',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
