# Generated by Django 2.1.4 on 2018-12-17 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0021_auto_20181217_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='Coupon_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user_coupon',
            name='Coupon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_book_server.Coupon'),
        ),
        migrations.AddField(
            model_name='user_coupon',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
