# Generated by Django 2.1.4 on 2018-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0022_auto_20181217_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='begin_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
    ]
