# Generated by Django 2.1.4 on 2018-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0023_auto_20181217_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='credits',
            field=models.IntegerField(default=10),
        ),
    ]
