# Generated by Django 2.1.4 on 2018-12-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0024_auto_20181217_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersheet',
            name='order_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
