# Generated by Django 2.1.4 on 2018-12-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0026_ordersheet_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheet',
            name='coupon_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='second_book_server.Coupon'),
        ),
    ]
