# Generated by Django 2.1.4 on 2018-12-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0028_auto_20181218_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheet',
            name='date',
            field=models.CharField(default='2018-1-1', max_length=20),
        ),
    ]
