# Generated by Django 2.1.4 on 2018-12-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0030_announcement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='an_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
