# Generated by Django 2.1.4 on 2018-12-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='university_name',
            new_name='university',
        ),
    ]
